using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using System.Diagnostics;

namespace Crypton.AvChat.Gui.Win32 {
    /// <summary>
    /// Win32 API Methods
    /// </summary>
    internal static class Win32Impl {

        /// <summary>
        /// Returns a pointer to the foreground window currently shown
        /// </summary>
        /// <returns></returns>
        [DllImport("user32.dll")]
        public static extern IntPtr GetForegroundWindow();

        /// <summary>
        /// Flashes the specified window. It does not change the active state of the window.
        /// </summary>
        /// <param name="pwfi">A pointer to a FLASHWINFO structure.</param>
        /// <returns>The return value specifies the window's state before the call to the FlashWindowEx function. If the window caption was drawn as active before the call, the return value is nonzero. Otherwise, the return value is zero.</returns>
        [DllImport("user32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool FlashWindowEx(ref FLASHWINFO pwfi);

        /// <summary>
        /// Retrieves the time of the last input event.
        /// </summary>
        /// <param name="plii">A pointer to a LASTINPUTINFO structure that receives the time of the last input event. </param>
        /// <returns>If the function succeeds, the return value is nonzero. If the function fails, the return value is zero.</returns>
        [DllImport("user32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool GetLastInputInfo(out PLASTINPUTINFO plii);

        /// <summary>
        /// Opens a given URL in user's default browser
        /// </summary>
        /// <param name="url"></param>
        public static void OpenUrl(string url) {
            MainForm frmMain = (MainForm)Application.OpenForms.Cast<Form>().FirstOrDefault(f => f is MainForm);
            try {
                Process.Start(url);
            }
            catch (Exception ex) {
                Trace.TraceError(ex.ToString());
                MessageBox.Show(frmMain, "Could not open the given URL, this may happen if the system is a bit slow (or the browser). Please try again", Application.ProductName, MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
   
        /// <summary> The RegisterHotKey function defines a system-wide hot key </summary>
        /// <param name="hwnd">Handle to the window that will receive WM_HOTKEY messages  generated by the hot key.</param>
        /// <param name="id">Specifies the identifier of the hot key.</param>
        /// <param name="fsModifiers">Specifies keys that must be pressed in combination with the key  specified by the 'vk' parameter in order to generate the WM_HOTKEY message.</param>
        /// <param name="vk">Specifies the virtual-key code of the hot key</param>
        /// <returns><c>true</c> if the function succeeds, otherwise <c>false</c></returns>
        /// <seealso cref="http://msdn.microsoft.com/en-us/library/ms646309(VS.85).aspx"/>
        [DllImport("user32.dll", SetLastError = true)]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool RegisterHotKey(IntPtr hWnd, int id, uint fsModifiers, uint vk);
    
    }
}
