//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crypton.AvChat.Win.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crypton.AvChat.Win.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html, body {
        ///    padding:0;
        ///    margin:0;
        ///    font-family: &apos;Segoe UI&apos;, Verdana, Geneva, &apos;DejaVu Sans&apos;, sans-serif;
        ///    font-size:8.25pt;
        ///}
        ///
        ///#topic {
        ///    display:none;
        ///}
        ///
        ///#messageList {
        ///    list-style-type:none;
        ///    line-height:150%;
        ///    margin:8px;
        ///    padding:0;
        ///    padding-bottom:8px;
        ///}
        ///
        ///.date {
        ///}
        ///
        ///.message {
        ///}
        ///
        ///.message-status {
        ///
        ///}
        ///
        ///.username {
        ///}
        ///
        ///.
        /// </summary>
        internal static string ChatBaseCss {
            get {
                return ResourceManager.GetString("ChatBaseCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Work mode colors */
        ///
        ///body
        ///{
        ///    color: white;
        ///    background-color: #202020 !important;
        ///}
        ///
        ///.date
        ///{
        ///    color: gray;
        ///    cursor: pointer;
        ///    margin-right:1ex;
        ///}
        ///
        ///.date.mine {
        ///    color:#ff71ff;
        ///}
        ///
        ///.message {
        ///}
        ///
        ///.message-status {
        ///    color: #74ff65;
        ///}
        ///
        ///.message-user .message {
        ///    margin-left:1ex;
        ///}
        ///
        ///.username {
        ///    color: #FFF654;
        ///    cursor:pointer;
        ///}
        ///
        ///.username.male {
        ///    color: #80A4BC;
        ///}
        ///
        ///.username.female {
        ///    color: ##D23EA6;
        ///}.
        /// </summary>
        internal static string WorkModeCss {
            get {
                return ResourceManager.GetString("WorkModeCss", resourceCulture);
            }
        }
    }
}
